version: '3'
services:
  postgres-db:
    image: postgres:11.10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "touristic_agencies"
