version: '3'
services:
  app:
    build: .
    depends_on:
      - 'db'
    ports:
      - '3000:3000'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      DB_HOST: 'db'
    volumes:
      - .:/usr/src/app/
    command: sh -c "./wait-for-postgres.sh db npm install && npm run dev"
  db:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - './sql_dump:/docker-entrypoint-initdb.d'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_MULTIPLE_DATABASES: 'touristic_agencies,test_touristic_agencies'
