export default {
  AGENCY_REPOSITORY: 'AGENCY_REPOSITORY',
  OFFICE_REPOSITORY: 'OFFICE_REPOSITORY',
  TOUR_REPOSITORY: 'TOUR_REPOSITORY',
  DIRECTION_REPOSITORY: 'DIRECTION_REPOSITORY',
  CATEGORY_REPOSITORY: 'CATEGORY_REPOSITORY',
  DATABASE_CONNECTION: 'DATABASE_CONNECTION'
} as const;
